:memo: add guidelines for open source code in fribyte
fribyte-code/.github pull request #1
Opened 2023-12-02 14:21 UTC by SindreKjelsrud

2023-12-02 14:21 UTC, SindreKjelsrud commented
Gjerne kom med ideer og skriv på det jeg har skrevet🫶

2023-12-02 14:28 UTC, mathiash98 reviewed
Bra tekst, vi bør nok ta med et avsnitt om "hva bær være open source" hvor vi sier at som standard vil vi at alle prosjekter er open source, med unntak av prosjekter med sensitiv informasjon som admin repo og (...)

2023-12-04 08:14 UTC, mathiash98 commented on retningslinjer.md
> +
```suggestion

### Hvilke repo bør være åpen kildekode?
Som grunnprinsipp ønsker vi at alle repo skal være åpen som standard. Men repo som "admin",
bør ikke være åpen da det inneholder navn og diverse informasjon som kan anses som privat.
Ellers har vi repo som CTF som blir holdt lukket i en periode da det inneholder svar på oppgaver.
Men generelt sett kan alt være åpent.

```

2023-12-04 10:12 UTC, timharek requested changes
Veldig bra initativ!

Hadde en kommentar til teksten. Men hadde også vært supert hvis teksten var kjørt gjennom en linter, som Prettier feks ☺️

2023-12-04 10:12 UTC, timharek commented on retningslinjer.md
> +Hvert prosjekt bør ha en README-fil som inneholder:
Uenig at alle prosjekter bør ha en README. Alle prosjekter _skal_ ha en README, og alle skal bidra til at det finnes 💭

2023-12-04 10:29 UTC, mathiash98 commented
> Veldig bra initativ!
> 
> Hadde en kommentar til teksten. Men hadde også vært supert hvis teksten var kjørt gjennom en linter, som Prettier feks ☺️

Vi kan legge til følgende konfig under `.vscode/settings.json` så blir de med vscode nudget:

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

Og følgende under `.vscode/extensions.json`, så vil ihvertfall de som bruker vscode bli nudget til å bruke prettier:

```json
{
  "recommendations": [
    "esbenp.prettier-vscode",
  ]
}
```

2023-12-04 11:40 UTC, mathiash98 approved these changes

2023-12-04 15:52 UTC, SindreKjelsrud commented
Gode poeng @mathiash98 og @timharek!! Ser du fiksa alt @mathiash98 så jeg tenker vi kan merge🫶

2023-12-04 15:54 UTC, merged